//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collective.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_campaign
    {
        public int campaign_id { get; set; }
        public string campaign_name { get; set; }
        public string campaign_manager_temp { get; set; }
        public string user_username { get; set; }
        public int campaign_rate { get; set; }
        public int campaign_agents_temp { get; set; }
        public string active_temp { get; set; }
        public string campaign_status { get; set; }
        public string campaign_location { get; set; }
        public System.DateTime campaign_datecreated { get; set; }
        public System.DateTime campaign_timestamp { get; set; }
        public string campaign_map { get; set; }
        public int campaign_contingency { get; set; }
        public int campaign_seats { get; set; }
        public int campaign_graceperiod { get; set; }
        public int archived { get; set; }
        public System.DateTime date_archived { get; set; }
        public string this_site { get; set; }
        public Nullable<decimal> ot_rate { get; set; }
    }
}
