//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collective.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teamschedule
    {
        public int teamschedule_id { get; set; }
        public int team_id { get; set; }
        public int shift_id { get; set; }
        public string team_days { get; set; }
        public System.TimeSpan teamschedule_timefrom { get; set; }
        public System.TimeSpan teamschedule_timeto { get; set; }
        public System.DateTime teamschedule_datebegin { get; set; }
        public int graveyard { get; set; }
        public int archived { get; set; }
        public System.DateTime date_archived { get; set; }
        public string team_label { get; set; }
        public string team_agents { get; set; }
        public System.DateTime date_assigned { get; set; }
        public int teamschedule_restdaylabel { get; set; }
        public string teamschedule_pre_ot_from { get; set; }
        public string teamschedule_pre_ot_to { get; set; }
        public string teamschedule_post_ot_from { get; set; }
        public string teamschedule_post_ot_to { get; set; }
        public long teamschedule_pre_ot_max { get; set; }
        public long teamschedule_post_ot_max { get; set; }
        public int schedule_isverified { get; set; }
        public Nullable<decimal> sched_rate { get; set; }
        public Nullable<decimal> sched_ot_rate { get; set; }
        public Nullable<int> sched_grace_period { get; set; }
        public long schedule_leave { get; set; }
        public long doubleshift { get; set; }
        public long isundertime { get; set; }
        public long assignedtoteam { get; set; }
    }
}
