//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collective.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_new
    {
        public int news_id { get; set; }
        public string news_name { get; set; }
        public System.DateTime news_date { get; set; }
        public bool news_active { get; set; }
        public string news_PictureLocation { get; set; }
        public string news_Link { get; set; }
    }
}
