//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collective.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_agent
    {
        public int agent_id { get; set; }
        public int campaign_id { get; set; }
        public int team_id { get; set; }
        public string agent { get; set; }
        public System.DateTime date_assigned { get; set; }
        public System.DateTime datecreated { get; set; }
        public int archived { get; set; }
        public System.DateTime date_archived { get; set; }
        public string this_site { get; set; }
        public long assignedtoteam { get; set; }
        public System.DateTime assignedtoteamdate { get; set; }
    }
}
