//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collective.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_profile
    {
        public int profile_id { get; set; }
        public string profile_empid { get; set; }
        public string user_username { get; set; }
        public string profile_fname { get; set; }
        public string profile_lname { get; set; }
        public string profile_mname { get; set; }
        public System.DateTime profile_birthday { get; set; }
        public string profile_contactnumber { get; set; }
        public string profile_civilstatus { get; set; }
        public string profile_gender { get; set; }
        public string profile_nationality { get; set; }
        public string profile_address { get; set; }
        public string profile_department { get; set; }
        public string profile_position { get; set; }
        public string profile_picture { get; set; }
    }
}
