//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collective.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_recipient
    {
        public int recipient_id { get; set; }
        public int messages_id { get; set; }
        public string user_username { get; set; }
        public int recipient_read { get; set; }
    }
}
