//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collective.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_team
    {
        public int team_id { get; set; }
        public int team_leader { get; set; }
        public string team_name { get; set; }
        public int campaign_id { get; set; }
        public string team_manager { get; set; }
        public System.DateTime date_created { get; set; }
        public int archived { get; set; }
        public System.DateTime date_archived { get; set; }
        public string this_site { get; set; }
    }
}
