//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collective.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_record_log
    {
        public long rec_id { get; set; }
        public System.DateTime dt_stamp { get; set; }
        public System.DateTime dt_stamp_end { get; set; }
        public string username { get; set; }
        public string station { get; set; }
        public string campaign { get; set; }
        public string status { get; set; }
        public string ip { get; set; }
        public string dt_stamp_day { get; set; }
        public string log_reason { get; set; }
        public string this_site { get; set; }
    }
}
