//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collective.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_toast
    {
        public int toast_id { get; set; }
        public string toast_username { get; set; }
        public System.DateTime toast_datetime { get; set; }
        public string toast_message { get; set; }
        public bool toast_read { get; set; }
        public System.DateTime toast_read_date { get; set; }
        public int toast_type { get; set; }
    }
}
