//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collective.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_message
    {
        public int message_id { get; set; }
        public string message_title { get; set; }
        public string message_content { get; set; }
        public string message_attachment { get; set; }
        public System.DateTime message_datecreated { get; set; }
        public System.DateTime message_timestamp { get; set; }
        public int user_id { get; set; }
        public string messages_sendto { get; set; }
        public string message_sendto { get; set; }
        public int message_priority { get; set; }
        public string messages_read { get; set; }
        public string this_site { get; set; }
    }
}
